name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          
      - uses: amondnet/25-action-android-gradle-build@v25
        with:
          gradle-version: 8.2
          android-sdk-version: '33'
          architecture: debug
          input-path: app/build.gradle
          output-directory: app/build/outputs/apk/debug
          
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/*.apk
